#!/usr/bin/env bash
usage() {
  cat <<EOF
Usage: $(basename $0) SNAPSHOTS INFILE

  Find snapshots under the SNAPSHOTS directory for RZX files listed in INFILE
  (where INFILE is typically generated by find-new-rzx-to-test.sh) and update
  rzx-work.txt accordingly.
EOF
  exit 1
}

[[ -z $2 ]] && usage

snapshots=$1
newrzx=$2
WORK=$SKOOLKIT_HOME/tools/rzx/rzx-work.txt

tmpfile=$(mktemp)
while read r; do
  rzx=$(echo "$r" | cut -f1 -d'|')
  len=$((${#rzx} - 4))
  z80=${rzx:0:$len}.z80
  [[ -f "$snapshots/$z80" ]] && echo "$r"
done < "$newrzx" > $tmpfile

worktmp=$(mktemp)
sort "$tmpfile" "$WORK" > "$worktmp"
cp "$worktmp" "$WORK"
rm -f "$tmpfile" "$worktmp"
echo "Updated $WORK"
