#!/usr/bin/env bash
set -e # Abort on errors

usage() {
  cat <<EOF
Usage: $(basename $0) [options]

  Create a release tarball and zip archive of SkoolKit.

Options:
  -h  Show this help
  -p  Use setup-pkg.py (for building a DEB or RPM package)
  -q  Be quiet
  -t  Write only the release tarball
EOF
  exit 1
}

info() {
  if [ $VERBOSE -eq 1 ]; then
    echo $*
  fi
}

if [ -z "$SKOOLKIT_HOME" ]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [ ! -d "$SKOOLKIT_HOME" ]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

cd $SKOOLKIT_HOME
VERSION=$(./skool2html.py -V 2>&1 | cut -f2 -d' ')
PKGNAME=skoolkit-$VERSION
PKGDIR=$PKGNAME

VERBOSE=1
WRITE_ZIP=1
SETUP=setup.py

while getopts ":hpqt" opt; do
  case $opt in
    h) usage ;;
    p) SETUP=setup-pkg.py; PKGNAME=skoolkit-pkg-$VERSION ;;
    q) VERBOSE=0 ;;
    t) WRITE_ZIP=0 ;;
  esac
done

DISTDIR=$SKOOLKIT_HOME/dist
ABSDIR=${DISTDIR}/${PKGDIR}
rm -rf ${ABSDIR}
DOCSDIR=${ABSDIR}/docs
mkdir -p $DOCSDIR
MANDIR=${ABSDIR}/man/man1
mkdir -p $MANDIR

rsync -aR \
  {bin2tap,skool2{asm,ctl,html,sft},sna2skool,tap2sna}.py \
  skoolkit/{__init__,bin2tap,ctlparser,defaults,disassembler,image,refparser,pngwriter,gifwriter,sftparser,skool{{,2}{asm,ctl,html,sft},macro,parser},sna{,2}skool,snapshot,tap2sna}.py \
  examples/48.rom.{ctl,ref} \
  resources/{skoolkit{,-dark,-green,-plum,-spectrum,-wide}.css,spectrum.ttf{,.txt}} \
  tests/{skoolkittest,test_{bin2tap,ctlparser,disassembler,image,skool{{,2}{asm,ctl,html,sft},macro,parser},refparser,sftparser,skoolkit,sna{2,}skool,snapshot,tap2sna}}.py \
  COPYING MANIFEST.in \
  $ABSDIR
cp -a $SETUP $ABSDIR/setup.py

# Documentation and man pages
cd $SKOOLKIT_HOME/sphinx
rm -rf build/*
if ! make html &> /dev/null; then
  echo "*** Error building documentation; aborting"
  exit 1
fi
rm -rf build/html/man
rsync -a --exclude=.buildinfo --exclude=objects.inv build/html/ $DOCSDIR
if ! make man &> /dev/null; then
  echo "*** Error building man pages; aborting"
  exit 1
fi
rsync -a build/man/*.py.1 $MANDIR

cd $DISTDIR

info "Creating ${DISTDIR}/${PKGNAME}.tar.xz"
tar acf ${PKGNAME}.tar.xz $PKGDIR

if [ $WRITE_ZIP -eq 1 ]; then
  info "Creating ${DISTDIR}/${PKGNAME}.zip"
  zip -9qr ${PKGNAME}.zip $PKGDIR
fi
