#!/bin/bash -e

declare -A SK_VERSIONS
SK_VERSIONS=(
  [20150523]=4.4
  [20150214]=4.3
  [20140308]=3.7
  [20131102]=3.6
)

ROM=/usr/share/spectrum-roms/48.rom

if (($# < 2)); then
  echo "Usage: $(basename $0) VERSION SKOOLKIT_VERSION"
  echo ""
  echo "  Attempts to build a specific version of the Spectrum ROM disassembly using a"
  echo "  specific version of SkoolKit."
  echo ""
  echo "  VERSION must be one of:"
  echo ""
  for v in ${!SK_VERSIONS[@]}; do
    echo "    $v"
  done | sort -r | column -c 80
  echo ""
  echo "  Environment variables:"
  echo "    SKOOLKIT_ARCHIVE - directory containing SkoolKit release tarballs"
  exit 1
fi

if [[ -z $SKOOLKIT_ARCHIVE ]]; then
    echo 'SKOOLKIT_ARCHIVE is not set; aborting'
    exit 1
fi
if [[ ! -d $SKOOLKIT_ARCHIVE ]]; then
    echo "SKOOLKIT_ARCHIVE=$SKOOLKIT_ARCHIVE: directory not found"
    exit 1
fi

D_VERSION=$1
SK_VERSION=$2

SK_VERSION_INT=$(echo $SK_VERSION | tr -d .)0
SK_VERSION_INT=${SK_VERSION_INT:0:3}

D_SK_VERSION=${SK_VERSIONS[$D_VERSION]}
if [[ -z $D_SK_VERSION ]]; then
  echo "Disassembly version not recognised: $D_VERSION"
  exit 1
fi

odir=rom-$D_VERSION-$SK_VERSION
rm -rf $odir
mkdir $odir
cd $odir

SK_DIR=skoolkit-$SK_VERSION
tar xf $SKOOLKIT_ARCHIVE/$SK_DIR.tar.*
SK_BUILD_DIR=${SK_DIR}-build
mv $SK_DIR $SK_BUILD_DIR

D_SK_DIR=skoolkit-$D_SK_VERSION
tar xf $SKOOLKIT_ARCHIVE/$D_SK_DIR.tar.*
SK_SRC_DIR=$D_SK_DIR-src
mv $D_SK_DIR $SK_SRC_DIR

cp -p $SK_SRC_DIR/examples/48.rom.{ctl,ref} $SK_BUILD_DIR
cd $SK_BUILD_DIR

if (($SK_VERSION_INT < 360)); then
  binfile=48.rom.bin
  cp -p $ROM $binfile
else
  binfile=$ROM
fi
./sna2skool.py -o 0 -H -c 48.rom.ctl $binfile > 48.rom.skool

./skool2html.py -t -d .. 48.rom.ref
