#!/usr/bin/env bash

# Validates XML using 'onsgmls'
# USAGE: validate-xhtml [DIR]
# Errors are printed on stderr
# If there is no output, there were no errors

if [ -z "$SKOOLKIT_HOME" ]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [ ! -d "$SKOOLKIT_HOME" ]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

DTD=$SKOOLKIT_HOME/DTD
if [ ! -d "$DTD" ]; then
  echo "Error: directory not found: $DTD"
  echo "Have you run 'make DTD' yet?"
  exit 1
fi

ONSGMLS=onsgmls
if ! which $ONSGMLS > /dev/null; then
  echo "You need to install $ONSGMLS (in package 'opensp') first"
  exit 1
fi

retval=0
DIR=${1:-.}
for html in $(find $DIR -name '*.html'); do
  $ONSGMLS -s -wxml -c$DTD/xhtml.soc $html || retval=1
done

exit $retval
