#!/usr/bin/env bash

. $(dirname $0)/ddiffs-functions

print_status() {
  text=$1
  quiet=${2:-0}
  if [ $quiet -eq 0 ]; then
    echo $text
  fi
}

run_cmd() {
  cmd=$1
  out=$2
  quiet=${3:-0}
  outfile=${4:-$out}
  error_out=$(mktemp)
  mkdir -p $(dirname $outfile)
  if [ $quiet -eq 0 ]; then
    echo -n "Writing $outfile..."
  fi
  if $cmd > $out 2> $error_out; then
    if grep -q ^WARNING: $error_out; then
      print_status "done (with warnings)" $quiet
    else
      print_status "done" $quiet
    fi
  else
    print_status "done (with errors)" $quiet
  fi
  rm -f $error_out
}

write_asms() {
  for suffix in '' '-load' '-save' '-start'; do
    skool=src/$(basename $skoolfile .skool)$suffix.skool
    if [ ! -f "$skool" ]; then
      continue
    fi
    for b in '' '-D' '-H'; do
      for c in '' '-l' '-u'; do
        for fix in '' '1' '2' '3'; do
          if [ -n "$fix" ]; then
            f="-f $fix"
            infix="-f$fix"
          else
            f=""
            infix=""
          fi
          for p in '' '-s' '-r'; do
            run_cmd "./skool2asm.py -q $b $c $f $p $skool" asm/$GAME$suffix$b$c$infix$p.asm
          done
        done
      done
    done
  done
}

dump_bin() {
  bin=$1

  [[ $GAME = rom ]] || offset=$(( 65536 - $(du -b $bin | cut -f1) ))
  hexdump -v -e '/1 "%_ad "' -e '/1 "%u\n"' $bin | while read addr byte; do
    [[ $GAME = rom ]] && printf "$%04X $%02X\n" $addr $byte || echo $(( addr + offset )) $byte
  done
}

write_bins() {
  for m in '' '-i' '-s' '-o' '-b'; do
    bin=bin/$GAME$m.bin
    run_cmd "./skool2bin.py $m src/$skoolfile $bin" /dev/null 0 $bin
    [ -f $bin ] && run_cmd "dump_bin $bin" bin/$GAME$m.dump
  done
}

write_ctls() {
  for b in '' '-h' '-l'; do
    run_cmd "./skool2ctl.py $b src/$skoolfile" ctl/$GAME$b.ctl
  done
}

write_genctls() {
  profile="$SNAPSHOT.profile"
  for b in '' '-l' '-h'; do
    run_cmd "./sna2ctl.py $snapshot_opts $b $SNAPSHOT" genctl/$GAME$b.ctl
    [[ -f $profile ]] && run_cmd "./sna2ctl.py $snapshot_opts $b -m $profile $SNAPSHOT" genctl/$GAME-m$b.ctl
  done
}

write_html() {
  for b in '' '-D' '-H'; do
    for c in '' '-u' '-l'; do
      gamedir=$GAME$b$c
      varopt=""
      reffile=""
      if [[ -z $c ]]; then
        [[ $b == -D ]] && varopt="--var pub=1" && reffile=$DHOME/sources/publish.ref
        [[ $b == -H ]] && varopt="--var pub=2" && reffile=$DHOME/sources/publish.ref
      fi
      echo -n "Writing $gamedir HTML disassembly..."
      ./skool2html.py $b $c -q -d html -c Config/GameDir=$gamedir $varopt src/$skoolfile $reffile
      echo "done"
    done
  done
}

write_skools() {
  (($sk_version_major > 6)) && lower=-l || lower=-L
  ctl=/tmp/${GAME}.ctl
  run_cmd "./skool2ctl.py src/$skoolfile" $ctl 1
  for b in '' '-H'; do
    for c in '' $lower; do
      run_cmd "./sna2skool.py $snapshot_opts -c $ctl $b $c $SNAPSHOT" skool/$GAME$b${c^^}.skool
    done
  done
  rm -f $ctl
}

write_sfts() {
  for b in '' '-h' '-l'; do
    run_cmd "./skool2sft.py $b src/$skoolfile" sft/$GAME$b.sft
  done
}

usage() {
  echo "Usage: $(basename $0) $GAMES TYPE [TYPE...]"
  echo ""
  echo "  TYPE can be one of: asm bin ctl genctl html skool sft all"
  exit 1
}

###############################################################################
# Begin...
###############################################################################
[ -z "$2" ] && usage

GAME=$1
read_ddiffsrc $GAME
skoolfile=$(basename $(ls -1 src/*.skool | grep -Ev '/.*(load|save|start).skool'))
[ "$GAME" = "rom" ] && snapshot_opts="-o 0"
sk_version=$(./skool2html.py -V 2>&1 | egrep -o '[0-9]+\.[0-9]+')
sk_version_major=$(echo $sk_version | cut -f1 -d.)
sk_version_minor=$(echo $sk_version | cut -f2 -d.)

shift
while [ "$1" != "" ]; do
  case "$1" in
    asm) write_asms ;;
    bin) write_bins ;;
    ctl) write_ctls ;;
    genctl) write_genctls ;;
    html) write_html ;;
    skool) write_skools ;;
    sft) write_sfts ;;
    all)
      write_asms
      write_bins
      write_ctls
      write_genctls
      write_html
      write_skools
      write_sfts
      ;;
    *) echo "Skipping unknown file type: '$1'" ;;
  esac
  shift
done
